name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build sender
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o sender_testchecker *.c*
      
    - name: build reciever
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o reciever_testchecker ./Reciever/*.c*
      
    - name: run sender
      run: ./sender_testchecker    
        
    - name: pipe sender and reciever
      run: ./sender_testchecker | ./reciever_testchecker

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21

